// <auto-generated />
namespace Diary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addmigrationSetLastNameMaxLenghtAndRequiredInStudentsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigrationSetLastNameMaxLenghtAndRequiredInStudentsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202402041654525_add-migration SetLastNameMaxLenghtAndRequiredInStudentsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
